// transpiler.ts — Walks the AST and emits JavaScript source code.

import {
  Block, Stmt, Expr,
  PrintStmt, VarDecl, AssignStmt, IfStmt, WhileStmt,
  FunctionDecl, ReturnStmt, ExprStmt,
  NumberLit, StringLit, BoolLit, Identifier,
  BinaryExpr, UnaryExpr, CallExpr,
} from "./parser";

export class Transpiler {
  private indent = 0;

  transpile(program: Block): string {
    const lines: string[] = [
      `// Generated by telugu-lang v0.1.0`,
      `"use strict";`,
      ``,
    ];
    lines.push(this.emitBlock(program, /* bare */ true));
    return lines.join("\n");
  }

  // ── block & statements ────────────────────────────────────────────────

  private emitBlock(block: Block, bare = false): string {
    if (bare) {
      return block.stmts.map((s) => this.emitStmt(s)).join("\n");
    }
    this.indent++;
    const body = block.stmts.map((s) => this.pad() + this.emitStmt(s)).join("\n");
    this.indent--;
    return `{\n${body}\n${this.pad()}}`;
  }

  private emitStmt(stmt: Stmt): string {
    switch (stmt.type) {
      case "PrintStmt":    return this.emitPrint(stmt);
      case "VarDecl":      return this.emitVarDecl(stmt);
      case "AssignStmt":   return this.emitAssign(stmt);
      case "IfStmt":       return this.emitIf(stmt);
      case "WhileStmt":    return this.emitWhile(stmt);
      case "FunctionDecl": return this.emitFunction(stmt);
      case "ReturnStmt":   return this.emitReturn(stmt);
      case "ExprStmt":     return `${this.emitExpr(stmt.expr)};`;
      case "Block":        return this.emitBlock(stmt);
    }
  }

  private emitPrint(stmt: PrintStmt): string {
    return `console.log(${this.emitExpr(stmt.expr)});`;
  }

  private emitVarDecl(stmt: VarDecl): string {
    const kw = stmt.isConst ? "const" : "let";
    const init = stmt.init !== null ? ` = ${this.emitExpr(stmt.init)}` : "";
    return `${kw} ${stmt.name}${init};`;
  }

  private emitAssign(stmt: AssignStmt): string {
    return `${stmt.name} = ${this.emitExpr(stmt.value)};`;
  }

  private emitIf(stmt: IfStmt): string {
    let out = `if (${this.emitExpr(stmt.cond)}) ${this.emitBlock(stmt.then)}`;
    if (stmt.else_) out += ` else ${this.emitBlock(stmt.else_)}`;
    return out;
  }

  private emitWhile(stmt: WhileStmt): string {
    return `while (${this.emitExpr(stmt.cond)}) ${this.emitBlock(stmt.body)}`;
  }

  private emitFunction(stmt: FunctionDecl): string {
    const params = stmt.params.join(", ");
    return `function ${stmt.name}(${params}) ${this.emitBlock(stmt.body)}`;
  }

  private emitReturn(stmt: ReturnStmt): string {
    return stmt.value ? `return ${this.emitExpr(stmt.value)};` : `return;`;
  }

  // ── expressions ───────────────────────────────────────────────────────

  private emitExpr(expr: Expr): string {
    switch (expr.type) {
      case "NumberLit":  return String(expr.value);
      case "StringLit":  return JSON.stringify(expr.value);
      case "BoolLit":    return expr.value ? "true" : "false";
      case "Identifier": return expr.name;
      case "BinaryExpr": return this.emitBinary(expr);
      case "UnaryExpr":  return this.emitUnary(expr);
      case "CallExpr":   return this.emitCall(expr);
    }
  }

  private emitBinary(expr: BinaryExpr): string {
    return `(${this.emitExpr(expr.left)} ${expr.op} ${this.emitExpr(expr.right)})`;
  }

  private emitUnary(expr: UnaryExpr): string {
    return `${expr.op}${this.emitExpr(expr.operand)}`;
  }

  private emitCall(expr: CallExpr): string {
    const args = expr.args.map((a) => this.emitExpr(a)).join(", ");
    return `${expr.callee}(${args})`;
  }

  // ── helpers ───────────────────────────────────────────────────────────

  private pad(): string {
    return "  ".repeat(this.indent);
  }
}
